<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (C) 2015-2026 HandcraftedBits

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.handcraftedbits</groupId>
  <artifactId>handcraftedbits-parent</artifactId>
  <packaging>pom</packaging>
  <name>HandcraftedBits Parent POM</name>
  <description>A parent POM used by HandcraftedBits projects</description>
  <url>https://github.com/handcraftedbits/handcraftedbits-parent</url>
  <version>${revision}${changelist}</version>
  <inceptionYear>2015</inceptionYear>

  <developers>
    <developer>
      <name>Curtiss Howard</name>
      <email>opensource@handcraftedbits.com</email>
      <organization>HandcraftedBits</organization>
      <organizationUrl>https://github.com/handcraftedbits</organizationUrl>
    </developer>
  </developers>
  <organization>
    <name>HandcraftedBits</name>
    <url>https://github.com/handcraftedbits</url>
  </organization>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>

  <scm>
    <url>https://github.com/handcraftedbits/handcraftedbits-parent</url>
    <connection>scm:git:git://github.com/handcraftedbits/handcraftedbits-parent.git</connection>
    <developerConnection>scm:git:git@github.com:handcraftedbits/handcraftedbits-parent.git</developerConnection>
  </scm>
  <issueManagement>
    <url>https://github.com/handcraftedbits/handcraftedbits-parent/issues</url>
    <system>GitHub Issues</system>
  </issueManagement>

  <properties>
    <revision>1.7.3</revision>
    <changelist>-SNAPSHOT</changelist>

    <license.type>ASL2</license.type>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <version.dep.handcraftedbits-codequality>1.3.1</version.dep.handcraftedbits-codequality>
    <version.maven.minimum>3.8.4</version.maven.minimum>

    <version.plugin.central-publishing>0.11.0</version.plugin.central-publishing>
    <version.plugin.enforcer>3.6.3</version.plugin.enforcer>
    <version.plugin.flatten>1.8.0</version.plugin.flatten>
    <version.plugin.gpg>3.2.8</version.plugin.gpg>
    <version.plugin.license>5.1.1</version.plugin.license>
    <version.plugin.resources>3.5.0</version.plugin.resources>
    <version.plugin.rewrite>6.46.1</version.plugin.rewrite>
    <version.plugin.versions>2.21.0</version.plugin.versions>
  </properties>

  <modules>
    <module>handcraftedbits-parent-java</module>
  </modules>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${version.plugin.resources}</version>
          <configuration>
            <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${version.plugin.versions}</version>
        </plugin>
        <plugin>
          <groupId>org.openrewrite.maven</groupId>
          <artifactId>rewrite-maven-plugin</artifactId>
          <version>${version.plugin.rewrite}</version>
          <dependencies>
            <dependency>
              <groupId>com.handcraftedbits</groupId>
              <artifactId>handcraftedbits-codequality</artifactId>
              <version>${version.dep.handcraftedbits-codequality}</version>
            </dependency>
          </dependencies>
          <configuration>
            <activeRecipes>
              <recipe>com.handcraftedbits.codequality.HandcraftedBits</recipe>
            </activeRecipes>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${version.plugin.enforcer}</version>
        <executions>
          <execution>
            <id>enforce-maven-version</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>${version.maven.minimum}</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>${version.plugin.flatten}</version>
        <configuration>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
          <updatePomFile>true</updatePomFile>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <!-- Release/deploy to Maven Central -->
    <profile>
      <id>release</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>

      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>${version.plugin.gpg}</version>
            <configuration>
              <signer>bc</signer>
            </configuration>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.openrewrite.maven</groupId>
            <artifactId>rewrite-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>verify-conventions</id>
                <phase>verify</phase>
                <goals>
                  <goal>dryRunNoFork</goal>
                </goals>
                <configuration>
                  <failOnDryRunResults>true</failOnDryRunResults>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <version>${version.plugin.central-publishing}</version>
            <extensions>true</extensions>
            <configuration>
              <publishingServerId>central</publishingServerId>
              <autoPublish>true</autoPublish>
              <waitUntil>validated</waitUntil>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <!-- Update copyright on source files -->
    <profile>
      <id>update-copyright</id>
      <activation>
        <activeByDefault>false</activeByDefault>
        <file>
          <exists>${basedir}/LICENSE</exists>
        </file>
      </activation>

      <build>
        <plugins>
          <plugin>
            <groupId>com.mycila</groupId>
            <artifactId>license-maven-plugin</artifactId>
            <version>${version.plugin.license}</version>
            <dependencies>
              <dependency>
                <groupId>com.handcraftedbits</groupId>
                <artifactId>handcraftedbits-codequality</artifactId>
                <version>${version.dep.handcraftedbits-codequality}</version>
              </dependency>
            </dependencies>
            <executions>
              <execution>
                <id>update-copyright</id>
                <phase>process-sources</phase>
                <goals>
                  <goal>format</goal>
                </goals>
                <configuration>
                  <aggregate>true</aggregate>
                  <licenseSets>
                    <licenseSet>
                      <header>license/${license.type}</header>
                      <headerDefinitions>
                        <headerDefinition>license/style/xmlstyle.xml</headerDefinition>
                      </headerDefinitions>
                      <includes combine.children="append">
                        <include>**/pom.xml</include>
                        <include>**/*.java</include>
                        <include>**/src/it/**/invoker.properties</include>
                        <include>**/src/it/**/verify.groovy</include>
                        <include>**/src/it/resources/**/*.properties</include>
                        <include>**/src/it/resources/**/*.xml</include>
                        <include>**/src/main/codequality/**/*.xml</include>
                        <include>**/src/main/resources/**/*.properties</include>
                        <include>**/src/main/resources/**/*.xml</include>
                        <include>**/src/test/resources/**/*.properties</include>
                        <include>**/src/test/resources/**/*.xml</include>
                      </includes>
                    </licenseSet>
                  </licenseSets>
                  <mapping>
                    <java>SLASHSTAR_STYLE</java>
                  </mapping>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
